### ISSUE TITLE
Unable to Propagate traceparent Header Between Two Micronaut Applications Using New Relic Java Agent

### ISSUE THREAD

**Issue by shahparthiv** [newrelic/newrelic-java-micronaut-http#20] opened 2024-11-19 07:55 UTC
have two Micronaut applications, micronaut-0 and micronaut-b, where micronaut-0 is making an HTTP request to an endpoint in micronaut-b. Below are the details of my setup:

Maven Dependencies for micronaut-0 and micronaut-b:
Micronaut HTTP Client Dependency:

```
<dependency>
  <groupId>io.micronaut</groupId>
  <artifactId>micronaut-http-client</artifactId>
</dependency>
```

New Relic Agent Dependencies:
```
<dependency>
  <groupId>com.newrelic.agent.java</groupId>
  <artifactId>newrelic-api</artifactId>
  <version>8.15.0</version>
</dependency>

<dependency>
  <groupId>com.newrelic.agent.java</groupId>
  <artifactId>newrelic-java</artifactId>
  <version>8.15.0</version>
  <scope>provided</scope>
  <type>zip</type>
</dependency>
```

Maven Plugin to Unpack New Relic Agent:

```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-dependency-plugin</artifactId>
  <version>3.1.1</version>
  <executions>
    <execution>
      <id>unpack-newrelic</id>
      <phase>package</phase>
      <goals>
        <goal>unpack-dependencies</goal>
      </goals>
      <configuration>
        <includeGroupIds>com.newrelic.agent.java</includeGroupIds>
        <includeArtifactIds>newrelic-java</includeArtifactIds>
        <overWriteIfNewer>true</overWriteIfNewer>
        <outputDirectory>${project.build.directory}</outputDirectory>
      </configuration>
    </execution>
  </executions>
</plugin>
```

**Problem:**
When I make a request from micronaut-0 to micronaut-b, I expect the traceparent header to be included in the request headers (as per W3C Trace Context). However, I don't see the traceparent header being sent or received on micronaut-b.

The same thing I have done using the following library and in that case the trace propagation is working fine.
```
<dependency>
  <groupId>io.micronaut</groupId>
  <artifactId>micronaut-http-client-jdk</artifactId>
</dependency>
```

Questions:

- How can I ensure that the New Relic agent propagates the traceparent header between micronaut-0 and micronaut-b?
- Do I need additional configuration for the Micronaut HTTP client(Netty based) to enable trace context propagation?
- Are there specific steps to manually instrument the Micronaut HTTP client(Netty based) for New Relic's distributed tracing?

**Comment by shahparthiv** [comment] 2024-11-19 07:57
Hi [gsidhwani-nr](https://github.com/gsidhwani-nr), It would be great if you could check this issue.

**Comment by dhilpipre** [comment] 2024-11-20 18:55
shahparthiv 
The instrumentation for the Micronaut Http Client takes care inserting three headers when the client makes an Http call.  It sent two W3C headers (traceparent and tracestate) and a New Relic Java agent DT header.  We have verified that all three are sent by the client and properly received on the receiving end.  We are able to see the distributed trace displayed in New Relic.
One possible explanation of why you don't see the headers is that there is a problem with the Java Agent starting or connecting to New Relic.   Distributed tracing headers are not populated until the Java agent connects to New Relic.
Can you verify that the Java Agent has started and reporting to New Relic?   Probably the best way to do this is to check the New Relic directory and see if it is generating a log file in the logs directory.   If the agent connects to New Relic then that application should be showing up in the New Relic UI.

Here's the documentation on installing and configuring the New Relic Java Agent
https://docs.newrelic.com/install/java/
Here's some troubleshooting documentation 
https://docs.newrelic.com/docs/apm/agents/java-agent/troubleshooting/no-data-appears-java/

**Comment by dhilpipre** [comment] 2024-12-02 14:19
Cannot reproduce.  closing

**Closed as completed by dhilpipre** 2024-12-02 14:19 UTC
Labels: bug
